apiVersion: v1
kind: Service
metadata:
  name: svc-web
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 32281
    protocol: TCP
    targetPort: 8000
  selector:
    app: nginx    
